trigger:
  branches:
    include:
  # Update which branch will trigger the pipeline  
    - development                                                                 
  paths:
    include:
  # Change the path to include the dataset name
    - powerbi/models/name-of-model/*                                     
pool:
  # Set build agent 
  name: Azure Pipelines
  vmImage: 'windows-latest'                                             
                                                     
# local variables - set these here
variables:
    # Change the value to include the dataset name
  - name: PBIDataset
    value: 'name-of-model'
    # XMLA Endpoint for the workspace (make sure to replace %20 with spaces)                                                   
  - name: PBIWorkspace
    value: 'powerbi://api.powerbi.com/v1.0/myorg/' 
    # Development Lifecycle Stage
  - name: PipelineStage
    value: 'development' 
    # Service Connection for using Service Principal     
  - name: ServiceConnection
    value: 'service-connection-name' 
    # Databricks Server/Workspace URL                           
  - name: DbxServer
    value: 'adb-.azuredatabricks.net' 
    # DBX Http path for the SQL Warehouse/Endpoint
  - name: DbxEndpoint
    value: '/sql/1.0/warehouses' 
    # DBX Catalog - leave as hive_metatstore for non-UC workspaces
  - name: DbxCatalog
    value: 'hive_metastore'                                     

steps:
  - template: ../templates/template-tabularmodel-pipeline.yml
    parameters:
      PBIDataset: $(PBIDataset)
      PBIWorkspace: $(PBIWorkspace)
      ServiceConnection: $(ServiceConnection)
      Environment: $(PipelineStage)
      DbxServer: $(DbxServer)
      DbxEndpoint: $(DbxEndpoint)
      DbxCatalog: $(DbxCatalog)
  