trigger:
 branches:
    include:
  # Update which branch will trigger the pipeline  
    - demo
 paths:
    include:
      - powerbi/workspaces/*

pool:
  vmImage: 'ubuntu-latest'
stages:

## Dev Group Workspaces
- stage: DevWorkspacesDeployment
  displayName: Deploy Power BI Workspaces
  jobs:
  - deployment: DeployGroups
    displayName: Deploy Power BI Workspaces via Template
    environment: 'development'
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../templates/template-powerbi-workspaces.yml
            parameters:
              keyVaultName: 'kv-aggreg8-dev'
              subscription: 'aggreg8-connection'
              folderPath: 'powerbi/workspaces/'
              environment: 'dev'
          
# ## TEST Deployment
# #- stage: TSTGroupDeployment
# #  displayName: Deploy Power BI Groups
# #  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
# #  jobs:
# #  - deployment: DeployGroups
# #    displayName: Deploy Power BI Groups via Template
# #    environment: 'test'
# #    workspace:
# #      clean: all
# #    strategy:
# #      runOnce:
# #        deploy:
# #          steps:
# #          - template: templates\template-powerbi-groups.yml
#             parameters:
#               keyVaultName: 'keyvault-name'
#               subscription: 'subscription-name'
#               folderPath: 'PowerBI/Groups'
#               environment: 'test'
          
# ## PRD Deployment
# - stage: PRDGroupDeployment
#   displayName: Deploy Power BI Groups
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
#   jobs:
#   - deployment: DeployGroups
#     displayName: Deploy Power BI Groups via Template
#     environment: 'Prod'
#     workspace:
#       clean: all
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: templates\template-powerbi-groups.yml
#             parameters:
#               keyVaultName: 'keyvault-name'
#               subscription: 'subscription-name'
#               folderPath: 'PowerBI/Groups'
#               environment: 'prod'
